### ISSUE TITLE
Export 3d Solid Mesh needs User defined Timeout

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/SimulationIO#5]
The user should be allowed to set the timeout (seconds/hours/days) for their package to run. Not all runs will take 2.7 hours. Some may take longer.

**Comment by saurabhpuri** [comment]
Fixed by Mike Jackson in the following commit:

https://github.com/BlueQuartzSoftware/SimulationIO/commit/72964e427a81b6c2e91513900e4774ec048a2853
